window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
window.isSafari=!1;if(/^((?!chrome|android).)*safari/i.test(navigator.userAgent)){window.isSafari=!0}
window.isSafariVersion='';if(window.isSafari){var version=(navigator.appVersion).match(/Version\/(\d+)\.(\d+)\.?(\d+)? Safari/);if(version!==null){window.isSafariVersion=[parseInt(version[1],10),parseInt(version[2],10),parseInt(version[3]||0,10)]}}
window.isIE=!!document.documentMode;function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t833_init(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var wrapper=rec.querySelector('.t833__sliderwrapper');if(!wrapper)return;var dataContainer=rec.querySelector('.t833');if(!dataContainer)return;var coverRecs=dataContainer.getAttribute('data-coverslider-rec-ids');t833_showOnCertainWidth(rec,wrapper);if(document.querySelector('#allrecords').getAttribute('data-tilda-mode')==='edit'){var recDemo=rec.querySelector('.t833__demo');t833_addAnimation(recDemo,wrapper);return}
if(coverRecs){coverRecs=coverRecs.split(',');Array.prototype.forEach.call(coverRecs,function(rec){var currentRec=document.querySelector('#rec'+rec);var currentWrapper=wrapper.cloneNode(!0);currentWrapper.style.position='absolute';if(currentRec){t833_addAnimation(currentRec,currentWrapper)}})}else{var nextBlock=rec.nextElementSibling;var prevBlock=rec.previousElementSibling;var currentWrapper=wrapper.cloneNode(!0);currentWrapper.style.position='absolute';if(nextBlock&&nextBlock.querySelector('.t-cover')){t833_addAnimation(nextBlock,currentWrapper)}else if(prevBlock&&prevBlock.querySelector('.t-cover')){t833_addAnimation(prevBlock,currentWrapper)}}}
function t833_showOnCertainWidth(rec,wrapper){currentClass=rec.getAttribute('class');classListArr=currentClass.split(' ');Array.prototype.forEach.call(classListArr,function(classItem){if(classItem.indexOf('t-screen')!==-1){wrapper.classList.add(classItem)}})}
function t833_addAnimation(currentRec,wrapper){if(!currentRec)return;currentRec.setAttribute('data-animationappear','off');currentRec.classList.remove('r_hidden');var currentRecType=currentRec.getAttribute('data-record-type');var isT941=currentRecType==='941';var isT996=currentRecType==='996';if(currentRecType==='396'){currentRec.querySelector('.t396__filter').insertAdjacentElement('afterend',wrapper);wrapper.style.zIndex='0'}
var coverWrapper;if(isT941){coverWrapper=currentRec.querySelector('.t941__cover-wrap')}else if(isT996){coverWrapper=currentRec.querySelector('.t996__cover-wrapper')}else{coverWrapper=currentRec.querySelector('.t-cover')}
if(coverWrapper){if(isT941){wrapper.classList.add('t941__cover');coverWrapper.appendChild(wrapper)}else if(isT996){wrapper.classList.add('t996__cover');coverWrapper.appendChild(wrapper)}else{coverWrapper.querySelector('.t-cover__filter').insertAdjacentElement('afterend',wrapper)}
wrapper.style.zIndex='0'}
var images=t833_createImageArr(wrapper);var imageCount=images.length;var imagesLoaded=0;for(var i=0;i<imageCount;i++){images[i].onload=function(){imagesLoaded++;if(imagesLoaded==imageCount&&currentRec.length!==0){setTimeout(function(){t833_changeSlide(currentRec)},3000)}}}
var slider=currentRec.querySelector('.t833__slider');var allSlides=currentRec.querySelectorAll('.t833__slide');var numberOfSlides=allSlides.length;if(numberOfSlides===3||numberOfSlides===2){Array.prototype.forEach.call(allSlides,function(slide){var cloneSlide=slide.cloneNode(!0);slider.appendChild(cloneSlide)})}}
function t833_createImageArr(wrapper){var imagesSrc=[];allSlides=wrapper.querySelectorAll('.t833__slide');Array.prototype.forEach.call(allSlides,function(slideItem){imagesSrc.push(slideItem.getAttribute('data-original'))});var images=[];Array.prototype.forEach.call(imagesSrc,function(image,i){images[i]=new Image();images[i].src=image});return images}
function t833_changeSlide(currentRec){var sliderWrapper=currentRec.querySelectorAll('.t833__sliderwrapper');Array.prototype.forEach.call(sliderWrapper,function(sliderItem){var isLoaded=sliderItem.getAttribute('data-loaded')&&sliderItem.getAttribute('data-loaded')==='yes'?!0:!1;if(!isLoaded){var slides=sliderItem.querySelectorAll('.t833__slide');var firstSlide=sliderItem.querySelector('.t833__slide:first-child');var numberOfSlides=slides.length;firstSlide.classList.add('t833__slide_fx1');setTimeout(function(){t833_kenBurns(slides,numberOfSlides,1)},500);sliderItem.setAttribute('data-loaded','yes')}});function t833_kenBurns(slides,numberOfSlides,i){if(i==numberOfSlides)i=0;slides[i].classList.add('t833__slide_fx');if(i===0&&slides[numberOfSlides-2]){slides[numberOfSlides-2].classList.remove('t833__slide_fx');slides[numberOfSlides-2].classList.remove('t833__slide_fx1')}
if(i===1&&slides[numberOfSlides-1]){slides[numberOfSlides-1].classList.remove('t833__slide_fx');slides[numberOfSlides-1].classList.remove('t833__slide_fx1');Array.prototype.forEach.call(slides,function(slide){slide.classList.remove('t833__slide_opacity')})}
if(i>1&&slides[i-2]){slides[i-2].classList.remove('t833__slide_fx');slides[i-2].classList.remove('t833__slide_fx1')}
setTimeout(function(){t833_kenBurns(slides,numberOfSlides,i+1)},5000)}}
function t688_init(recId){t_onFuncLoad('t_card__moveClickOnCard',function(){t_card__moveClickOnCard(recId)});t_onFuncLoad('t_card__addFocusOnTab',function(){t_card__addFocusOnTab(recId)})}
function t688_unifyHeights(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t688');if(!container)return;var rows=rec.querySelectorAll('.t688__row');if(window.innerWidth>=960){for(var i=0;i<rows.length;i++){var row=rows[i];var maxHeight=0;var cols=row.querySelectorAll('.t-col:not(.t688__featured):not(.t688__inner-col)');var textWrappers=row.querySelectorAll('.t688__textwrapper');var featureds=row.querySelectorAll('.t688__featured');var colEl=row.querySelector('.t688__col');for(var j=0;j<cols.length;j++){var col=cols[j];var colText=col.querySelector('.t688__textwrapper_inner');var colTextHeight=colText.offsetHeight;if(colTextHeight>maxHeight)maxHeight=colTextHeight}
for(var j=0;j<textWrappers.length;j++){textWrappers[j].style.height=maxHeight+'px'}
if(colEl){for(var j=0;j<featureds.length;j++){var featured=featureds[j];var colStyle=getComputedStyle(colEl,null);var colPaddingTop=parseInt(colStyle.paddingTop)||0;var colPaddingBottom=parseInt(colStyle.paddingBottom)||0;var colHeight=col.clientHeight-(colPaddingTop+colPaddingBottom);featured.style.height=colHeight+'px'}}}}else{var textWrappers=rec.querySelectorAll('.t688__textwrapper');var featureds=rec.querySelectorAll('.t688__featured');var col=rec.querySelector('.t688__col');if(col){var colStyle=getComputedStyle(col,null);var colPaddingTop=parseInt(colStyle.paddingTop)||0;var colPaddingBottom=parseInt(colStyle.paddingBottom)||0;var colHeight=col.clientHeight-(colPaddingTop+colPaddingBottom);for(var i=0;i<featureds.length;i++){featureds[i].style.height=colHeight+'px'}}
for(var i=0;i<textWrappers.length;i++){textWrappers[i].style.height='auto'}}}
function t121_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var wrapperBlock=rec.querySelector('.t121');var videoLazy=rec.querySelector('.t-video-lazyload');if(videoLazy){t_onFuncLoad('t_video_lazyload__setHeight',function(){var videoHeight=videoLazy.getAttribute('data-videolazy-height');if(videoHeight!=='540px')return;t_video_lazyload__setHeight(videoLazy);window.addEventListener('resize',function(){t_video_lazyload__setHeight(videoLazy)});if(!wrapperBlock)return;wrapperBlock.addEventListener('displayChanged',function(){t_video_lazyload__setHeight(videoLazy)})})}
var videoCarrier=rec.querySelector('.t-video-carier');if(!videoCarrier)return;var screenMin=rec.getAttribute('data-screenmin');var screenMax=rec.getAttribute('data-screenmax');var isLoad=!1;if(window.innerWidth<parseInt(screenMin,10)||window.innerWidth>parseInt(screenMax,10))return;window.addEventListener('scroll',t_throttle(function(){if(!isLoad){var videoCarrierOffsetTop=videoCarrier.getBoundingClientRect().top+window.pageYOffset;var videoCarrierHeight=parseInt(window.getComputedStyle(videoCarrier).height,10);var windowScrollTop=window.pageYOffset;var windowHeight=window.innerHeight;if(windowScrollTop+windowHeight>videoCarrierOffsetTop-500&&windowScrollTop<videoCarrierOffsetTop+videoCarrierHeight+501){t_onFuncLoad('processYoutubeVideo',function(){processYoutubeVideo(videoCarrier,videoCarrier.style.height)});isLoad=!0}}}));var event=document.createEvent('HTMLEvents');event.initEvent('scroll',!0,!1);window.dispatchEvent(event)}
function t670_init(recid,isEditMode){var rec=document.getElementById('rec'+recid);if(!rec)return;var image=rec.querySelector('.t-img');if(image){if(image.complete){t670_addImageEvents(recid,isEditMode)}else{image.addEventListener('load',function(){t670_addImageEvents(recid,isEditMode)});image.addEventListener('error',function(){t670_addImageEvents(recid,isEditMode)})}}else{t670_addImageEvents(recid,isEditMode)}}
const t670_postMessages={youtube:{pause:'{"event":"command","func":"pauseVideo","args":""}',play:'{"event":"command","func":"playVideo","args":""}',},rutube:{pause:'{"type":"player:pause","data":"{}"}',play:'{"type":"player:play","data":"{}"}',},vimeo:{pause:'{"method":"pause","value":"true"}',play:'{"method":"play","value":"true"}',},};function t670_addImageEvents(recid,isEditMode){var rec=document.getElementById('rec'+recid);t670_imageHeight(rec);t670_show(rec);t670_hide(rec);t670_addArrowHandlers(rec);t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)});if(isEditMode){t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)})}
var wrapper=rec.querySelector('.t670');if(wrapper){wrapper.addEventListener('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t_onFuncLoad('t_slds_positionArrows',function(){t_slds_positionArrows(recid)})})}}
function t670_handleRutube(videoWrap,videoLazy){var videoId=videoLazy.getAttribute('data-videolazy-id');if(videoId)videoId=videoId.replace(/[^\w-]/g,'');if(!videoId)return;var videoHash=videoLazy.getAttribute('data-videolazy-hash');if(videoHash)videoHash=videoHash.replace(/[^\w-]/g,'');var existingIframe=videoWrap.querySelector('iframe.t670__rutube-iframe');if(!existingIframe){var src='https://rutube.ru/play/embed/'+videoId+'/?autoplay=1&muted=1&playsinline=1';if(videoHash)src+='&p='+videoHash;videoWrap.innerHTML='';var iframe=document.createElement('iframe');iframe.className='t670__rutube-iframe';iframe.setAttribute('allow','autoplay; fullscreen');iframe.setAttribute('allowfullscreen','');iframe.setAttribute('frameborder','0');iframe.style.width='100%';iframe.style.height='100%';iframe.style.display='block';iframe.src=src;videoWrap.appendChild(iframe)}else{try{existingIframe.contentWindow.postMessage(t670_postMessages.rutube.play,'*')}catch(e){console.warn('Failed to send play message to Rutube iframe:',e)}}}
function t670_show(rec){var playBtns=rec.querySelectorAll('.t670__play');Array.prototype.forEach.call(playBtns,function(play){var itemWrap=play.closest('.t670__imgwrapper');var image=itemWrap.querySelector('.t-slds__bgimg');var videoWrap=itemWrap.querySelector('.t670__wrap-video');var videoLazy=videoWrap.querySelector('.t-video-lazyload');play.addEventListener('click',function(event){event.preventDefault();videoWrap.style.display='block';image.style.opacity=0;var type=videoLazy.getAttribute('data-videolazy-type');if(type==='rutube'){t670_handleRutube(videoWrap,videoLazy)}else{t_onFuncLoad('t_video_lazyload__addVideo',function(){t_video_lazyload__addVideo(videoLazy)})}})})}
function t670_pauseVideo(videoWrap){if(!videoWrap)return;var iframe=videoWrap.querySelector('iframe');if(iframe&&iframe.contentWindow&&iframe.src){var videoSRC=iframe.src;if(videoSRC.indexOf('&enablejsapi=1')!==-1){iframe.contentWindow.postMessage(t670_postMessages.youtube.pause,'*')}
if(videoSRC.indexOf('rutube')!==-1){iframe.contentWindow.postMessage(t670_postMessages.rutube.pause,'*')}
if(videoSRC.indexOf('vimeo')!==-1&&videoSRC.indexOf('&api=1')!==-1){iframe.contentWindow.postMessage(t670_postMessages.vimeo.pause,'*')}}
var videoEl=videoWrap.querySelector('video');if(videoEl&&typeof videoEl.pause==='function'){try{videoEl.pause()}catch(e){console.warn('t670: Failed to pause video element:',e)}}}
function t670_hide(rec){var videoWraps=rec.querySelectorAll('.t670__wrap-video');rec.addEventListener('updateSlider',function(){Array.prototype.forEach.call(videoWraps,function(videoWrap){t670_pauseVideo(videoWrap);var hasIframe=videoWrap.querySelector('iframe');if(!hasIframe){videoWrap.style.display='none'}})})}
function t670_addArrowHandlers(rec){if(!rec)return;if(rec.t670ArrowsInitialized){return}
rec.t670ArrowsInitialized='true';rec.addEventListener('click',function(event){var arrow=event.target.closest('.t-slds__arrow_wrapper');if(!arrow)return;t670_pauseAllVideos(rec)})}
function t670_pauseAllVideos(rec){if(!rec)return;var videoWraps=rec.querySelectorAll('.t670__wrap-video');Array.prototype.forEach.call(videoWraps,function(videoWrap){t670_pauseVideo(videoWrap);var hasIframe=videoWrap.querySelector('iframe');if(!hasIframe){videoWrap.style.display='none';var imgWrapper=videoWrap.closest('.t670__imgwrapper');if(imgWrapper){var bgImg=imgWrapper.querySelector('.t-slds__bgimg');if(bgImg){bgImg.style.opacity=1}}}})}
function t670_imageHeight(rec){var images=rec.querySelectorAll('.t670__separator');Array.prototype.forEach.call(images,function(img){var width=parseInt(img.getAttribute('data-slider-image-width'))||0;var height=parseInt(img.getAttribute('data-slider-image-height'))||0;var ratio=height/width;var padding=ratio*100;img.style.paddingBottom=padding+'%'})}
function t698_onSuccess(form){t_onFuncLoad('t_forms__onSuccess',function(){t_forms__onSuccess(form)})}
function t698_fixcontentheight(recId){var rec=document.getElementById('rec'+recId);var cover=rec.querySelector('.t-cover');var coverFilter=rec.querySelector('.t-cover__filter');var coverCarrier=rec.querySelector('.t-cover__carrier');var coverWrapper=rec.querySelector('.t-cover__wrapper');var coverContainer=rec.querySelector('.t-cover__container');var coverStyle=getComputedStyle(cover,null);var coverPaddingTop=parseInt(coverStyle.paddingTop)||0;var coverPaddingBottom=parseInt(coverStyle.paddingBottom)||0;var coverHeight=cover.clientHeight-(coverPaddingTop+coverPaddingBottom);var hookContent=rec.querySelector('div[data-hook-content]');var hookContentHeight=hookContent.offsetHeight;if(hookContentHeight>300&&coverHeight<hookContentHeight){var newHookContentHeight=hookContentHeight+120;if(newHookContentHeight>1000)newHookContentHeight+=100;console.log('auto correct cover height: '+newHookContentHeight);cover.style.height=newHookContentHeight+'px';if(coverFilter)coverFilter.style.height=newHookContentHeight+'px';if(coverCarrier)coverCarrier.style.height=newHookContentHeight+'px';if(coverWrapper)coverWrapper.style.height=newHookContentHeight+'px';if(coverContainer)coverContainer.style.height=newHookContentHeight+'px';if(window.isMobile===!1){setTimeout(function(){if(coverCarrier.querySelector('iframe')){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(coverCarrier,newHookContentHeight+'px')}},2000)}}}
function t890_init(recId,offset){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t890');if(!container)return;var windowOffset=offset||window.innerHeight;rec.setAttribute('data-animationappear','off');rec.style.opacity=1;window.addEventListener('scroll',t_throttle(function(){if(window.pageYOffset>windowOffset){container.style.display='block'}else{t890__fadeOut(container)}},200));var isSafari=/^((?!chrome|android).)*safari/i.test(navigator.userAgent);rec.addEventListener('click',function(e){if(e.target.closest('.t890__arrow')){isSafari?t890__animateScrollPolyfill(0):t890__scrollToTop()}})}
function t890__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},20)}
function t890__scrollToTop(){if(window.isIE){window.scrollTo(0,0)}else{window.scrollTo({left:0,top:0,behavior:'smooth',})}}
function t890__animateScrollPolyfill(target){var documentHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var bottomViewportPoint=documentHeight-document.documentElement.clientHeight;if(target>bottomViewportPoint)target=bottomViewportPoint;if(target===window.pageYOffset)return!1;var currentPosition=window.pageYOffset;var step=(target-currentPosition)/30;var difference=window.pageYOffset;var timerID=setInterval(function(){difference+=step;window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if((target-currentPosition<0&&window.pageYOffset<=target)||(target-currentPosition>0&&window.pageYOffset>=target)){clearInterval(timerID);document.body.removeAttribute('data-scrollable')}},10)}
window.requestAnimationFrame=(function(){return(window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(callback){window.setTimeout(callback,1000/60)})})();function t270_scroll(hash,offset){if(!hash)return;t270_checkLoad(hash,offset);var excludeHashes=['#!/tproduct/','#!/tab/','#opencart'];if(excludeHashes.includes(hash)){return!0}
var isHistoryChangeAllowed=window.location.hash!==hash;var wrapperBlock=document.querySelector('.t270');var dontChangeHistory=wrapperBlock?Boolean(wrapperBlock.getAttribute('data-history-disabled')):!1;t270_scrollToEl(hash,offset);if(!dontChangeHistory&&isHistoryChangeAllowed){if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
return!0}
function t270_checkLoad(hash,offset){if(window.t270_loadChecked)return;var sliderWrappers=document.body.querySelectorAll('.t-slds__items-wrapper');if(!sliderWrappers.length)return;var lastWrapper=sliderWrappers[sliderWrappers.length-1];var sliderImgs=lastWrapper?lastWrapper.querySelectorAll('.t-slds__bgimg'):[];var lastImg=sliderImgs[sliderImgs.length-1];var imageUrl=lastImg?window.getComputedStyle(lastImg).backgroundImage:'';imageUrl=imageUrl.substring(5,imageUrl.length-2);var preloaderImg=document.createElement('img');preloaderImg.src=imageUrl?imageUrl:'';preloaderImg.addEventListener('load',function(){t270_scroll(hash,offset);window.t270_loadChecked=!0})}
function t270_scrollToEl(hash,offset){var SCROLL_DURATION_MS=500;var body=document.body;if(body.getAttribute('data-scroll'))return;var scrollTargetY=t270_getTarget(hash,offset);if(isNaN(scrollTargetY))return;var canSmoothScroll=window.CSS&&window.CSS.supports('scroll-behavior','smooth')&&'scrollBehavior' in document.documentElement.style;var userAgent=navigator.userAgent.toLowerCase();var isAndroid=userAgent.indexOf('android')!==-1;if(window.isMobile&&!isAndroid&&canSmoothScroll){body.setAttribute('data-scroll','true');window.scrollTo({left:0,top:scrollTargetY,behavior:'smooth',});setTimeout(function(){body.removeAttribute('data-scroll')},SCROLL_DURATION_MS)}else{t270_smoothScrollTo(scrollTargetY,SCROLL_DURATION_MS)}}
function t270_smoothScrollTo(targetY,duration=500){var body=document.body;var startY=window.scrollY||window.pageYOffset;var deltaY=targetY-startY;var startTime=performance.now();function easeInOutQuad(t){return Math.pow(t,2)}
function scroll(){var currentTime=performance.now();var elapsedTime=Math.min((currentTime-startTime)/duration,1);var ease=easeInOutQuad(elapsedTime);window.scrollTo(0,startY+deltaY*ease);if(elapsedTime<1){requestAnimationFrame(scroll)}else{body.removeAttribute('data-scroll');body.removeAttribute('data-scrollable');window.scrollTo(0,targetY)}}
body.setAttribute('data-scroll','true');body.setAttribute('data-scrollable','true');requestAnimationFrame(scroll)}
function t270_getTarget(hash,offset){var target;try{if(hash.substring(0,1)==='#'){target=document.getElementById(hash.substring(1))}else{target=document.querySelector(hash)}}catch(event){console.log('Exception t270: '+event.message);return}
if(!target){target=document.querySelector('a[name="'+hash.substr(1)+'"], div[id="'+hash.substr(1)+'"]');if(!target)return}
target=parseInt(target.getBoundingClientRect().top+window.pageYOffset-offset,10);target=Math.max(target,0);return target}